# report_generator.py
# Generates downloadable TXT and PDF crop disease reports from AgriVision prediction data.

import os
from datetime import datetime


def generate_txt_report(data: dict) -> str:
    """
    Formats all prediction data into a clean plain-text report string.

    Args:
        data: prediction response dict (same shape returned by /predict)
              Expected keys: crop_type, prediction, severity, recommendation,
              weather, gps_info

    Returns:
        Formatted multi-line string ready to be sent as a .txt download.
    """
    pred    = data.get("prediction", {})
    sev     = data.get("severity", {})
    rec     = data.get("recommendation", {})
    weather = data.get("weather", {})

    timestamp  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    crop       = data.get("crop_type", "Unknown")
    disease    = pred.get("disease_display", "Unknown")
    confidence = pred.get("confidence", 0)
    severity   = sev.get("level") or "Healthy"
    gps        = data.get("gps_info") or "Not available"
    spray      = weather.get("advice") or "Not available"

    lines = [
        "==========================================",
        "     AGRIVISION CROP DISEASE REPORT",
        "==========================================",
        f"Date & Time : {timestamp}",
        f"Crop        : {crop}",
        f"Disease     : {disease}",
        f"Confidence  : {confidence}%",
        f"Severity    : {severity}",
        f"GPS Region  : {gps}",
        f"Weather     : {spray}",
        "------------------------------------------",
        "             AI RECOMMENDATIONS",
        "------------------------------------------",
    ]

    # Immediate Actions
    immediate = rec.get("immediate_actions", [])
    if immediate:
        lines.append("\nImmediate Actions:")
        for i, action in enumerate(immediate, 1):
            lines.append(f"  {i}. {action}")

    # Treatment
    treatment = rec.get("treatment", [])
    if treatment:
        lines.append("\nTreatment:")
        for i, t in enumerate(treatment, 1):
            lines.append(f"  {i}. {t}")

    # Recovery Time
    recovery = rec.get("recovery_time", "")
    if recovery:
        lines.append(f"\nExpected Recovery: {recovery}")

    # Preventive Measures
    measures = rec.get("preventive_measures", [])
    if measures:
        lines.append("\nPreventive Measures:")
        for i, m in enumerate(measures, 1):
            lines.append(f"  {i}. {m}")

    # Neighbouring Crop Risk
    risk = rec.get("neighbouring_crop_risk", "")
    if risk:
        lines.append(f"\nNeighbouring Crop Risk: {risk}")

    lines.extend([
        "\n==========================================",
        "  Generated by AgriVision | Matrix Fusion 4.0",
        "==========================================",
    ])

    return "\n".join(lines)


def generate_pdf_report(data: dict, output_path: str) -> str:
    """
    Generates a clean A4 PDF report from prediction data using reportlab.

    Layout: green title (#2d8a4e), plain readable body text.
    All recommendation sections are rendered as numbered lists.

    Args:
        data: prediction response dict (same shape as generate_txt_report)
        output_path: full path where the .pdf file should be written

    Returns:
        output_path on success

    Raises:
        ImportError if reportlab is not installed
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    pred    = data.get("prediction", {})
    sev     = data.get("severity", {})
    rec     = data.get("recommendation", {})
    weather = data.get("weather", {})

    timestamp  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    crop       = data.get("crop_type", "Unknown")
    disease    = pred.get("disease_display", "Unknown")
    confidence = pred.get("confidence", 0)
    severity   = sev.get("level") or "Healthy"
    gps        = data.get("gps_info") or "Not available"
    spray      = weather.get("advice") or "Not available"

    GREEN = colors.HexColor("#2d8a4e")
    DARK  = colors.HexColor("#1a1a1a")
    GRAY  = colors.HexColor("#555555")

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "AgriTitle", parent=styles["Title"],
        textColor=GREEN, fontSize=18, spaceAfter=4,
    )
    heading_style = ParagraphStyle(
        "AgriHeading", parent=styles["Heading2"],
        textColor=GREEN, fontSize=12, spaceBefore=12, spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "AgriBody", parent=styles["Normal"],
        textColor=DARK, fontSize=10, leading=16,
    )
    meta_style = ParagraphStyle(
        "AgriMeta", parent=styles["Normal"],
        textColor=GRAY, fontSize=10, leading=16,
    )

    # Ensure parent directory exists
    parent_dir = os.path.dirname(output_path)
    if parent_dir:
        os.makedirs(parent_dir, exist_ok=True)

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=inch, rightMargin=inch,
        topMargin=inch, bottomMargin=inch,
    )

    story = []

    # Title block
    story.append(Paragraph("AgriVision Crop Disease Report", title_style))
    story.append(Paragraph("AI Crop Intelligence for Indian Farmers — Matrix Fusion 4.0", meta_style))
    story.append(Spacer(1, 0.2 * inch))

    # Report meta fields
    story.append(Paragraph("Report Details", heading_style))
    for label, value in [
        ("Date &amp; Time", timestamp),
        ("Crop",            crop),
        ("Disease",         disease),
        ("Confidence",      f"{confidence}%"),
        ("Severity",        severity),
        ("GPS Region",      gps),
        ("Weather",         spray),
    ]:
        story.append(Paragraph(f"<b>{label}:</b>  {value}", meta_style))

    story.append(Spacer(1, 0.1 * inch))

    # Immediate Actions
    immediate = rec.get("immediate_actions", [])
    if immediate:
        story.append(Paragraph("Immediate Actions", heading_style))
        for i, action in enumerate(immediate, 1):
            story.append(Paragraph(f"{i}. {action}", body_style))

    # Treatment
    treatment = rec.get("treatment", [])
    if treatment:
        story.append(Paragraph("Treatment", heading_style))
        for i, t in enumerate(treatment, 1):
            story.append(Paragraph(f"{i}. {t}", body_style))

    # Recovery Time
    recovery = rec.get("recovery_time", "")
    if recovery:
        story.append(Paragraph("Expected Recovery Time", heading_style))
        story.append(Paragraph(recovery, body_style))

    # Preventive Measures
    measures = rec.get("preventive_measures", [])
    if measures:
        story.append(Paragraph("Preventive Measures", heading_style))
        for i, m in enumerate(measures, 1):
            story.append(Paragraph(f"{i}. {m}", body_style))

    # Neighbouring Crop Risk
    risk = rec.get("neighbouring_crop_risk", "")
    if risk:
        story.append(Paragraph("Neighbouring Crop Risk", heading_style))
        story.append(Paragraph(risk, body_style))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Generated by AgriVision | Matrix Fusion 4.0", meta_style))

    doc.build(story)
    return output_path
